// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("rescript/lib/js/list.js");
var $$Array = require("rescript/lib/js/array.js");
var $$String = require("rescript/lib/js/string.js");
var Caml_format = require("rescript/lib/js/caml_format.js");

var inputStr = "1,3,4,1,5,2,1,1,1,1,5,1,5,1,1,1,1,3,1,1,1,1,1,1,1,2,1,5,1,1,1,1,1,4,4,1,1,4,1,1,2,3,1,5,1,4,1,2,4,1,1,1,1,1,1,1,1,2,5,3,3,5,1,1,1,1,4,1,1,3,1,1,1,2,3,4,1,1,5,1,1,1,1,1,2,1,3,1,3,1,2,5,1,1,1,1,5,1,5,5,1,1,1,1,3,4,4,4,1,5,1,1,4,4,1,1,1,1,3,1,1,1,1,1,1,3,2,1,4,1,1,4,1,5,5,1,2,2,1,5,4,2,1,1,5,1,5,1,3,1,1,1,1,1,4,1,2,1,1,5,1,1,4,1,4,5,3,5,5,1,2,1,1,1,1,1,3,5,1,2,1,2,1,3,1,1,1,1,1,4,5,4,1,3,3,1,1,1,1,1,1,1,1,1,5,1,1,1,5,1,1,4,1,5,2,4,1,1,1,2,1,1,4,4,1,2,1,1,1,1,5,3,1,1,1,1,4,1,4,1,1,1,1,1,1,3,1,1,2,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,2,5,1,2,1,1,1,1,1,1,1,1,1";

function parseInput(input) {
  return List.map(Caml_format.caml_int_of_string, $$String.split_on_char(/* ',' */44, input));
}

function updateFish(fishTimer) {
  if (fishTimer === 0) {
    return [
            6,
            8
          ];
  } else {
    return [
            fishTimer - 1 | 0,
            undefined
          ];
  }
}

function passDay(fishes) {
  var match = List.fold_left((function (param, next) {
          var newFishes = param[1];
          var origFishes = param[0];
          var match = updateFish(next);
          var newFish = match[1];
          var updated = match[0];
          if (newFish !== undefined) {
            return [
                    {
                      hd: updated,
                      tl: origFishes
                    },
                    {
                      hd: newFish,
                      tl: newFishes
                    }
                  ];
          } else {
            return [
                    {
                      hd: updated,
                      tl: origFishes
                    },
                    newFishes
                  ];
          }
        }), [
        /* [] */0,
        /* [] */0
      ], fishes);
  return List.append(List.rev(match[0]), List.rev(match[1]));
}

function passDays(_day, _fishes) {
  while(true) {
    var fishes = _fishes;
    var day = _day;
    if (day <= 0) {
      return fishes;
    }
    var updated = passDay(fishes);
    _fishes = updated;
    _day = day - 1 | 0;
    continue ;
  };
}

function part1(param) {
  var input = parseInput(inputStr);
  var out = $$Array.of_list(passDays(50, input));
  console.log("OUT", out);
  return out.length;
}

console.log("Part 1", part1(undefined));

var exampleInputStr = "3,4,3,1,2";

exports.exampleInputStr = exampleInputStr;
exports.inputStr = inputStr;
exports.parseInput = parseInput;
exports.updateFish = updateFish;
exports.passDay = passDay;
exports.passDays = passDays;
exports.part1 = part1;
/*  Not a pure module */
